# -*- coding: utf-8 -*-
"""DribyaDristi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/108B0QWNqErDBWFzzWiPte9cXGuuMqt8J

# Preparing Dataset
**Importing Dependencies**
"""

import os
from os.path import isfile
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import cv2
from sklearn.model_selection import train_test_split
from keras.preprocessing.image import load_img
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D

"""**Loading dataset**"""

import os
print(os.listdir('/content/'))

from google.colab import drive
import zipfile
import os

# Mount Google Drive (if your file is in Drive)
drive.mount('/content/drive')

# Path to your zip file
zip_path = '/content/drive/MyDrive/DribyaDristi/asl_alphabet_train.zip'

# Extract the zip file
extract_path = '/content/asl_dataset'
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

dataset_path="/content/asl_dataset/asl_alphabet_train"

"""Getting image paths"""

def getImagePaths(dataset_path):
    image_paths = []
    for root, dirs, files in os.walk(dataset_path):
      for file in files:
          image_paths.append(os.path.join(root, file))
    return image_paths

image_paths=getImagePaths(dataset_path)
print(len(image_paths))
train_paths, test_paths = train_test_split(image_paths, test_size=0.2, random_state=42)

"""Creating data frame"""

def createDataFrame(image_paths):
    labels = [os.path.basename(os.path.dirname(path)) for path in image_paths]
    df = pd.DataFrame({'image': image_paths, 'label': labels})
    return df
train=createDataFrame(train_paths)
test=createDataFrame(test_paths)

print(len(image_paths))
print(len(train_paths))
print(len(test_paths))
print(train)
print(test)

from tqdm.notebook import tqdm

def extract_features(images):
    features = []
    for image in tqdm(images):
        img = load_img(image, color_mode =  "grayscale" , target_size=(48, 48))
        img = np.array(img)
        features.append(img)
    features = np.array(features)
    features = features.reshape(len(features),48,48,1)
    return features

train_features = extract_features(train['image'])
test_features = extract_features(test['image'])
x_train = train_features/255.0
x_test = test_features/255.0

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(train['label'])
LabelEncoder()

y_train = le.transform(train['label'])
y_test = le.transform(test['label'])

num_classes = train['label'].nunique()
print(f"Number of unique classes: {num_classes}")

y_train = to_categorical(y_train, num_classes=num_classes)
y_test = to_categorical(y_test, num_classes=num_classes)

print(x_train.shape)
print(y_train.shape)
label_order = le.classes_
print("Label order:", label_order)

"""Showing random image from the dataset"""

def showRandomImage(image_paths):
  random_image_path = random.choice(image_paths)
  print("Random image path:", random_image_path)
  image = plt.imread(random_image_path)
  plt.imshow(image)
  plt.show()

showRandomImage(image_paths)

print(images.shape)
random_image_np_array = random.choice(images)
print(random_image_np_array.shape)
print(random_image_np_array)




from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D

"""**Build the CNN Model**"""

model = Sequential()
# convolutional layers
model.add(Conv2D(128, kernel_size=(3,3), activation='relu', input_shape=(48,48,1)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

model.add(Conv2D(256, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

model.add(Conv2D(512, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

model.add(Conv2D(512, kernel_size=(3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.4))

model.add(Flatten())
# fully connected layers
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.3))
# output layer
model.add(Dense(num_classes, activation='softmax')) # num_classes should be 29 or equal to the actual number of classes in your dataset

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'] )

model.fit(x= x_train,y = y_train, batch_size = 128, epochs = 20, validation_data = (x_test,y_test))

model_json = model.to_json()
with open("DribyaDristi.json",'w') as json_file:
    json_file.write(model_json)
model.save("Dribya_Dristi.h5")

import shutil
from google.colab import files

# Path to your folder
folder_path = '/content/DribyaDristi'

# Name of the zip file
zip_file = 'DribyaDristi.zip'

# Zip the folder
shutil.make_archive('DribyaDristi', 'zip', folder_path)

# Download the zipped file
files.download(zip_file)

import io
import matplotlib.pyplot as plt
from tensorflow import keras

# Path to the directory containing the saved model
model_path = '/content/Dribya_Dristi.h5'

# Load the model
model = keras.models.load_model(model_path)

model.summary()

print(model.input_shape)



from google.colab import drive
drive.mount('/content/drive')

def showRandomImage(image_paths):
  random_image_path = random.choice(image_paths)
  print("Random image path:", random_image_path)
  image = plt.imread(random_image_path)
  plt.imshow(image)
  plt.show()

showRandomImage(image_paths)

from keras.preprocessing.image import load_img, img_to_array
import numpy as np

def ef(image):
    img = load_img(image,color_mode =  "grayscale",target_size=(48, 48) )
    feature = np.array(img)
    feature = feature.reshape(1,48,48,1)
    return feature/255.0

label = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'del', 'nothing', 'space']

def showRandomImage(image_paths):
  random_image_path = random.choice(image_paths)
  print(random_image_path)
  return random_image_path



image = showRandomImage(image_paths)
img = ef(image)
pred = model.predict(img)
# print(pred.argmax())
pred_label = label[pred.argmax()]
print("model prediction is ",pred_label)